name: Deploy to EC2

on:
  push:
    branches:
      - main 
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Add SSH Key and Set Permissions
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Start SSH agent and add key
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | ssh-add - <<< "${{ secrets.EC2_SSH_PASSPHRASE }}"

    - name: SSH into EC2 and Pull Latest Code
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_PATH }}
          git pull origin main
          sudo systemctl restart httpd
        EOF

