name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Create SSH Directory and Add SSH Key
      run: |
        mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa  # Set the right permissions for the SSH key

    - name: Start SSH agent and add key
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa

    - name: SSH into EC2 and Pull Latest Code
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_PATH }}
          git pull origin main
          sudo systemctl restart httpd
        EOF

